mLender/Models/Receipt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mLender.Models
{
    public class Receipt
    {
        public string type { get; set; }
        public string receipt_no { get; set; }
        public string member_number { get; set; }
        public string description { get; set; }
        public string loan_no { get; set; }
        public DateTime receipt_date { get; set; }
        public string debit_account { get; set; }
        public string reference_number { get; set; }
        public decimal amount { get; set; }

        //decimal item_amount = 0;
                     
    }
    public class NonMemberWalletReceipt
    {
        public string type { get; set; }
        public string receipt_no { get; set; }
        public string IDNo { get; set; }
        public string description { get; set; }
        public string reference_number { get; set; }
        public string MobileNo { get; set; }
        public DateTime receipt_date { get; set; }
        public string debit_account { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public string AuditId { get; set; }
        public DateTime AuditTime { get; set; }
    }
    public class OtherReceipts
    {
        public string type { get; set; }
        public string Name { get; set; }
        public string receipt_no { get; set; }
        public string description { get; set; }
        public string reference_number { get; set; }
        public DateTime receipt_date { get; set; }
        public string debit_account { get; set; }
        public string credit_account { get; set; }
        public decimal Amount { get; set; }
        public string AuditId { get; set; }
        public DateTime AuditTime { get; set; }
    }
}

mLender/Controllers/ReceiptController.cs
using Dapper;
using Microsoft.AspNet.Identity;
using mLender.Models;
using mLender.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mLender.Controllers
{
    [AccessDeniedAuthorize(Roles = "Manager,Admin,Agent")]


    public class ReceiptController : Controller
    {

        private static string ConnectionString =
            ConfigurationManager.ConnectionStrings["JIOKOE"].ConnectionString;
        private SqlConnection sqlConnection = new SqlConnection(ConnectionString);
        
        private JiokoeDbContext JiokoeDb = new JiokoeDbContext();

        oErrorLog oErrorLog = new oErrorLog();

        DateTime audit_time = DateTime.Now;


        [Authorize]
        public ActionResult Index()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();
                    var list_receipts = sqlConnection.Query<Receipt>("getReceipts", null).ToList();
                    return View(list_receipts);
                }
            }
            catch (Exception ex)
            {

                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult CombinedReceipt()
        {
            try
            {
                using (sqlConnection)
                {

                    sqlConnection.Open();

                    //get ledger bank to debit

                    IEnumerable<Ledger> ledgers =
                        sqlConnection.Query<Ledger>("get_Ledger_Banks", null, commandType: CommandType.StoredProcedure);

                    ViewBag.ledgers = new SelectList(ledgers, "code", "name");


                    //GET ALL active members

                    IEnumerable<MembersDetails> members = sqlConnection.Query<MembersDetails>
                    ("get_members_name_and_Number", null, commandType: CommandType.StoredProcedure);

                    ViewBag.members = new SelectList(members, "member_number", "fullname");


                    return View();
                }
            }
            catch (Exception ex)
            {

                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult CombinedReceipt(Receipt model)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    var receipt = new Receipt();
                    var systemuser = HttpContext.User.Identity.GetUserName();
                    receipt.amount = model.amount;
                    receipt.debit_account = model.debit_account;
                    receipt.loan_no = model.loan_no;
                    receipt.member_number = model.member_number;
                    receipt.receipt_date = model.receipt_date;
                    receipt.reference_number = model.reference_number;
                    receipt.type = model.type;
                    var audit_id = systemuser;

                    var save_receipt = sqlConnection.Execute("[saveCombinedReceipt]", new
                    {
                        receipt.member_number,
                        receipt.loan_no,
                        receipt.type,
                        receipt.amount,
                        receipt.receipt_date,
                        receipt.debit_account,
                        receipt.reference_number,
                        audit_id,
                        audit_time
                    }, commandType: CommandType.StoredProcedure);


                    return Json("Receipt made successfully", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {

                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }

        //
        // GET: /ReceiptContribution/Create

        [Authorize]

        public ActionResult Create()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();
                    //get member to recipt
                    IEnumerable<MembersDetails> members_list = sqlConnection.Query
                        <MembersDetails>("get_members_name_and_Number", null,
                       commandType: CommandType.StoredProcedure);
                    ViewBag.members_list =
                        new SelectList(members_list, "member_number", "fullname");

                    //get ledget to debit

                    IEnumerable<Ledger> ledgers = sqlConnection.Query<Ledger>
                            ("get_ledger_to_Debit", null, commandType: CommandType.StoredProcedure);
                    ViewBag.debit_ledgers = new SelectList(ledgers, "code", "name");

                    return View();
                }

            }
            catch (Exception ex)
            {

                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }

        

        //
        // GET: /ReceiptContribution/Edit/5
        [Authorize]

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ReceiptContribution/Edit/5

        [HttpPost]
        [Authorize]

        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ReceiptContribution/Delete/5
        [Authorize]

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ReceiptContribution/Delete/5

        [HttpPost]
        [Authorize]

        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public JsonResult get_Member_expectations(string member_number,string from_date)
        {
            try
            {
                DateTime date = Convert.ToDateTime(from_date);
                using (sqlConnection)
                {
                    sqlConnection.Open();
                    
                    var expectations = sqlConnection.Query("get_Member_Expectation",
                        new { 
                            member_number,
                            date 
                        }, commandType: CommandType.StoredProcedure);
                    return Json(expectations, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }
        //[Authorize]
        [HttpGet]
        public ActionResult NonMemberReceipt()
        {
           SqlConnection sqlConnection = new SqlConnection(ConnectionString);

            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();
                    //get ledger bank to credit

                    IEnumerable<Ledger> ledgers =
                        sqlConnection.Query<Ledger>("get_Ledger_Banks", null, commandType: CommandType.StoredProcedure);
                    ViewBag.ledgers = new SelectList(ledgers, "code", "name");
                }

                return View();
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        } 
        [HttpGet]
        public ActionResult OtherReceipts()
        {
           SqlConnection sqlConnection = new SqlConnection(ConnectionString);

            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();
                    //get ledger bank to credit

                    IEnumerable<Ledger> ledgers =
                        sqlConnection.Query<Ledger>("get_Ledger_Banks", null, commandType: CommandType.StoredProcedure);
                    ViewBag.ledgers = new SelectList(ledgers, "code", "name");
                }

                return View();
            }
            catch (Exception ex)
            {
                oErrorLog.WriteErrorLog(ex.Message);
                throw new Exception(ex.Message);
            }
        }
        [HttpPost]
        public ActionResult NonMemberReceipt(NonMemberWalletReceipt model)
        {
            SqlConnection sqlConnection = new SqlConnection(ConnectionString);
            try
                {
                    using (sqlConnection)
                    {
                        sqlConnection.Open();

                        var receipt = new NonMemberWalletReceipt();
                        var systemuser = HttpContext.User.Identity.GetUserName();
                        receipt.Credit = model.Credit;
                        receipt.debit_account = model.debit_account;
                        receipt.IDNo = model.IDNo;
                        receipt.MobileNo = model.MobileNo;
                        receipt.receipt_date = model.receipt_date;
                        receipt.reference_number = model.reference_number;
                        receipt.type = "Wallet";
                        var audit_id = systemuser;

mLender/Views/Receipt/Index.cshtml
@model IEnumerable<mLender.Models.Receipt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Html.Partial("~/Views/Shared/_LeftMenu.cshtml")

}
<style type="text/css">
    #receipts td {
        white-space: nowrap;
        font-size: 95%;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>


<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<!--Data table references-->

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<!--sweet alert for message display-->
@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>



<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>

<h4 style="text-align:center">Receipt List</h4>

<p>
    @Html.ActionLink("Create New", "combinedreceipt", new { }, new { @class = "btn btn-sm btn-success glyphicon  glyphicon-plus new_receipt", @style = "color:white" })
</p>
<div class="panel panel-default  col-md-10">
    <div class="bootstrap-admin-panel-content">
        <table class="table table-striped table-responsive" id="receipts">
            <thead>
                <tr>

                    <th>
                        @Html.DisplayName("Receipt No")
                    </th>
                    <th>
                        @Html.DisplayName("Member")
                    </th>
                    <th>
                        @Html.DisplayName("Type")
                    </th>
                    <th>
                        @Html.DisplayName("Description")
                    </th>

                    <th>
                        @Html.DisplayName("Receipt Date")
                    </th>
                    <th>
                        @Html.DisplayName("Ref No")
                    </th>
                    <th>
                        @Html.DisplayName("Amount")
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.receipt_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.member_number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>

                    <td>
                        @item.receipt_date.ToShortDateString()
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.reference_number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.amount)
                    </td>
                    <td class="hidden">
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<!--data tables-->
<script type="text/javascript">

    $('#receipts').DataTable(
        {
            "bPaginate": true, "bLengthChange": true, "bFilter": true, "bSort": true, "bInfo": true, "bAutoWidth": true, "aoColumns": [
                null,
                null,
                null, null, null, null, null, null]
        });

</script>

mLender/Views/Receipt/NonMemberReceipt.cshtml
@model mLender.Models.NonMemberWalletReceipt

@{
    ViewBag.Title = "NonMemberReceipt";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Html.Partial("~/Views/Shared/_LeftMenu.cshtml")

}
<!--Scripts-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />


<!--sweet alert for message display-->
@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>



<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>


@using (Html.BeginForm("nonmemberreceipt", "Receipt", new { ReturnUrl = ViewBag.Returnurl }, FormMethod.Post,
            new { @class = "bootstrap-admin-small-form col-md-6", @id = "nonMember" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>WalletReceipt</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IDNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDNo, new { htmlAttributes = new { @class = "form-control",
              required = "required"
       
       } })
            @Html.ValidationMessageFor(model => model.IDNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control",
              required = "required"
       
       } })
            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Bank Account", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(model => model.debit_account,
                                (SelectList)ViewBag.ledgers, "--Select Bank Account--",
                                   htmlAttributes: new
                                        {
                                            required = "required",
                                            @class = "form-control receipt",
                                                            @id = "bank",

                                                        })
            @Html.ValidationMessageFor(model => model.debit_account)
        </div>
    </div>
        <div class="form-group">
            @Html.Label("Receipt date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.receipt_date, "{0:dd/MMM/yyyy}", htmlAttributes: new
          {
              @class = "form-control dtPicker receipt",
              required = "required",
              placeholder = "Enter Receipt Date",
              id = "receipt_date"
          })
                @Html.ValidationMessageFor(model => model.receipt_date, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Reference No", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reference_number, new { htmlAttributes = new { @class = "form-control" ,
              required = "required"
           
           } })
                @Html.ValidationMessageFor(model => model.reference_number, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credit, new { htmlAttributes = new { @class = "form-control" ,
              required = "required"
           
           } })
                @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    //datepickers
     $(".dtPicker").datepicker({ maxDate: '0', dateFormat: 'dd/mm/yy' });
    $(".dtPicker ").each(function () {
        $(this).DisablePastingAndEdit();
    })
    
</script>