mLender/Controllers/MiscSettingsController.cs
using Dapper;
using mLender.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mLender.Controllers
{
    public class MiscSettingsController : Controller
    {
        private static string ConnectionString =
               ConfigurationManager.ConnectionStrings["JIOKOE"].ConnectionString;
        private SqlConnection sqlConnection = new SqlConnection(ConnectionString);

        private MiscellaneousSettings miscellaneous = new MiscellaneousSettings();

        private bool is_new = true;

        //
        // GET: /MiscSettings/
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();


                    var list_charge = sqlConnection.Query<MiscellaneousSettings>("get_miscellaneous_charges",
                        new { }, commandType: CommandType.StoredProcedure).ToList();

                    return View(list_charge);

                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        //
        // GET: /MiscSettings/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MiscSettings/Create
        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    //populate interest ledger account..get revenue group
                    IEnumerable<Ledger> revenue_account =
                        sqlConnection.Query<Ledger>("get_ledgers", new { }, commandType: CommandType.Text);

                    ViewBag.revenue_account = new SelectList(revenue_account, "code", "name");

                    //get charges type
                    IEnumerable<ChargeTypes> charges = sqlConnection.Query<ChargeTypes>("get_charges", new { },
                        commandType: CommandType.StoredProcedure);

                    ViewBag.charges = new SelectList(charges, "code", "type");





                    return View();

                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        //
        // POST: /MiscSettings/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(MiscellaneousSettings miscellaneous)
        {
            var settings = new MiscellaneousSettings();
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    settings.Name = miscellaneous.Name;
                    settings.Account_No = miscellaneous.Account_No;
                    settings.default_amount = miscellaneous.default_amount;
                    settings.Percentage = miscellaneous.Percentage;
                    settings.type = miscellaneous.type;

                    var rows_affected = sqlConnection.Execute("save_miscellaneous_Charges", new
                    {
                        settings.Name,
                        settings.Account_No,
                        settings.default_amount,
                        settings.Percentage,
                        settings.type,
                        is_new
                    }, commandType: CommandType.StoredProcedure);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //
        // GET: /MiscSettings/Edit/5
        [Authorize]
        public ActionResult Edit(string id)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    //populate interest ledger account..get revenue group
                    IEnumerable<Ledger> revenue_account =
                        sqlConnection.Query<Ledger>("select l.code code, l.name  from ledger l join " +
                        "ledger_group lg on lg.code = l.ledger_group and lg.class_code =@code ", new { code = 4000 }, commandType: CommandType.Text);

                    ViewBag.revenue_account = new SelectList(revenue_account, "code", "name");
                    //get charges type
                    IEnumerable<ChargeTypes> charges = sqlConnection.Query<ChargeTypes>("get_charges", new { },
                        commandType: CommandType.StoredProcedure);

                    ViewBag.charges = new SelectList(charges, "code", "type");

                    var charge = sqlConnection.Query<MiscellaneousSettings>
                        ("get_miscellaneous_charge", new { type = id }, commandType: CommandType.StoredProcedure).SingleOrDefault();
                    return View(charge);
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        //
        // POST: /MiscSettings/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(string id, MiscellaneousSettings miscellaneous)
        {
            try
            {
                sqlConnection.Open();

                is_new = false;
                miscellaneous.type = id;
                return Create(miscellaneous);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //
        // GET: /MiscSettings/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MiscSettings/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

mLender/Views/MiscSettings/Create.cshtml
@model mLender.Models.MiscellaneousSettings

@{

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />


<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>



@using (Html.BeginForm("create", "MiscSettings",
           new { ReturnUrl = ViewBag.Returnurl }, FormMethod.Post,
            new
            {
                @id = "misc_setting",
                @class = "bootstrap-admin-small-form "
            }

        ))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Miscellaneous Charges Settings</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name, htmlAttributes: new
       {
           @class = "form-control text",
           required = "required",
           type = "text",
           autocomplete = "off",
           id = "name"
       })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.Label("Ledger Account")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Account_No,
                                                    (SelectList)ViewBag.revenue_account, "--Select Account--",
                                                    htmlAttributes: new
                                                    {
                                                        required = "required",
                                                        @class = "form-control ",
                                                        @id = "revenue_account"

                                                    })
            @Html.ValidationMessageFor(model => model.Account_No, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.Label("Is Percantage?")
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(model => model.Percentage)
            @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.Label("Default Amount")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.default_amount, htmlAttributes: new
       {
           @class = "form-control money",
           required = "required",
           type = "number",
           autocomplete = "off",
           id = "default_amount",
           @min="0.00"
       })
            @Html.ValidationMessageFor(model => model.default_amount, "", new { @class = "text-danger" })
        </div>
        <div class="editor-label">
            @Html.Label("Charge Type")
        </div>
        <div class="form-group">
            @Html.DropDownListFor(model => model.type, (SelectList)ViewBag.charges, "--Select Charge Type--",
                        new { @class="form-control",  @required = "required" })

            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })

        </div>

        <div></div><p></p>
        <p>
            <button class="btn btn-lg btn-primary"> Save</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">

    $(".money").each(function (i, obj) {
        $(this).onlyNumb();
    });
</script>

<!--Check for alphabet only-->
<script type="text/javascript">
    $(".text").each(function (i, obj) {
        $(this).onlyAlphabets();
    });
</script>

mLender/Views/MiscSettings/Edit.cshtml
@model mLender.Models.MiscellaneousSettings

@{
    ViewBag.Title = "Edit Misc Charges";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />


<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>



@using (Html.BeginForm("edit", "MiscSettings",
           new { ReturnUrl = ViewBag.Returnurl }, FormMethod.Post,
            new
            {
                @id = "misc_setting",
                @class = "bootstrap-admin-small-form "
            }

        ))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MiscellaneousSettings</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name, htmlAttributes: new
    {
       @class = "form-control text",
       required = "required",
       type = "text",
       autocomplete = "off",
       id = "name"
    })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.Label("Ledger Account")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Account_No,
                                                    (SelectList)ViewBag.revenue_account, "--Select Account--",
                                                    htmlAttributes: new
                                                    {
                                                        required = "required",
                                                        @class = "form-control ",
                                                        @id = "revenue_account"

                                                    })
            @Html.ValidationMessageFor(model => model.Account_No, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Percentage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Percentage, true)
            @Html.ValidationMessageFor(model => model.Percentage)
        </div>

        <div class="editor-label">
            @Html.Label("Default Amount")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.default_amount, htmlAttributes: new
       {
           @class = "form-control money",
           required = "required",
           type = "number",
           autocomplete = "off",
           id = "default_amount",
           @min="0.00"
       })
            @Html.ValidationMessageFor(model => model.default_amount, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.Label("Charge Type")
        </div>
        <div class="form-group">
            @Html.DropDownListFor(model => model.type, (SelectList)ViewBag.charges, "--Select Charge Type--",
                        new { @class="form-control",  @required = "required" })

            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })

        </div>
        <p>
            <input class="btn btn-lg btn-primary" type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mLender/Views/MiscSettings/Index.cshtml
@model IEnumerable<mLender.Models.MiscellaneousSettings>

@{
    ViewBag.Title = "Misc Charges";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<p>
    @Html.ActionLink("Charge", "Create", new { },
    new { @class = "btn btn-lg btn-success glyphicon  glyphicon-plus", @style = "color:white" })

    <div class="panel-heading label-default "><h5 style="text-align:center">Miscellaneous Charges</h5></div>

</p>



@if (TempData["Success"] != null)
{
    <div class="alert alert-success bootstrap-admin-alert">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Success</h4>
        <p>@TempData["Success"]</p>
    </div>
}
else if (@TempData["Error"] != null)
{
    <div class="alert alert-danger bootstrap-admin-alert">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Error</h4>
        <p>@TempData["Error"]</p>
    </div>
}
<div class="panel panel-default">
    <div class="bootstrap-admin-panel-content">
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayName("Account")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Percentage)
                </th>
                <th>
                    @Html.DisplayName("Default Amount")
                </th>
                <th>
                    @Html.DisplayName("Charge Type")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Account_No)
                    </td>
                    <td>
                        @Html.YesNo(item.Percentage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.default_amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.type)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.type }) |
                        @Html.ActionLink("Delete", "#", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>