mLender/Models/Ledger.cs
using Dapper;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Script.Services;
using System.Web.Services;

namespace mLender.Models
{
    public class Ledger
    {


        public string Class { get; set; }
        public string Ledger_group { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Allow_Overdraft { get; set; }
        public bool IsBank { get; set; }



    }
}

mLender/Controllers/LedgerController.cs
using Dapper;
using mLender.Models;
using mLender.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mLender.Controllers
{
    [AccessDeniedAuthorize(Roles = "Manager,Admin")]

    public class LedgerController : Controller
    {
        private static string ConnectionString =
            ConfigurationManager.ConnectionStrings["JIOKOE"].ConnectionString;
        private SqlConnection sqlConnection = new SqlConnection(ConnectionString);
        private Ledger ledger = new Ledger();
        private JiokoeDbContext JiokoeDb = new JiokoeDbContext();
        public bool IsNew = true;
        bool IsDeleted = false;
        string ledger_code = "";
        private LedgerRepository ledgerRepository = new LedgerRepository();
        oErrorLog oError = new oErrorLog();

        //
        // GET: /Ledger/
        [Authorize]

        public ActionResult Index()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    List<Ledger> List_ledger = new List<Ledger>();
                    List_ledger = sqlConnection.Query<Ledger>("get_ledger_Accounts",
                        null, commandType: System.Data.CommandType.StoredProcedure).ToList();
                    return View(List_ledger);
                }
            }
            catch (Exception ex)
            {

                TempData["Error"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpPut]
        [Authorize]

        public ActionResult index(string code)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    var affected_row = sqlConnection.Execute
                        ("update ledger set IsDeleted=1 where code=@code",
                        new { ledger_code = code }, commandType: CommandType.Text);

                    return View("Index");

                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        //
        // GET: /Ledger/Details/5
        [Authorize]

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Ledger/Create
        [Authorize]

        public ActionResult Create()
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    //list classes
                    IEnumerable<MainLedgerClass> main_classes = sqlConnection.Query<MainLedgerClass>
                        ("select code,class from main_ledger_classes");

                    ViewBag.main_classes = new SelectList(main_classes, "code", "class");


                    //list sub classes/groups

                    IEnumerable<Ledger_Group> ledger_group =
                        sqlConnection.Query<Ledger_Group>
                        ("select code, group_name from ledger_group order by code", null,
                        commandType: CommandType.Text).ToList();

                    ViewBag.ledger_group = new SelectList(ledger_group, "code", "group_name");

                    return View(ledger);
                }
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }

        }

        //
        // POST: /Ledger/Create

        [HttpPost]
        [Authorize]

        public JsonResult Create(Ledger model)
        {
            try
            {
                var insertLedger = ledgerRepository.AddLedger(IsNew,model);
                TempData["Success"] = "Ledger details saved succesfully";

                return Json(TempData["Success"].ToString(), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                oError.WriteErrorLog(ex.Message);
                TempData["Error"] = "Details not saved! " + ex.Message;
                return Json(TempData["Error"].ToString(), JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /Ledger/Edit/5

        public ActionResult Edit(string id)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    //list main classes
                    List<MainLedgerClass> main_classes = sqlConnection.Query<MainLedgerClass>
                       ("select code,class from main_ledger_classes").ToList();

                    ViewBag.main_classes = new SelectList(main_classes, "code", "class");

                    //list sub ledgers

                    //list sub classes/groups

                    List<Ledger_Group> ledger_group =
                        sqlConnection.Query<Ledger_Group>
                        ("select code, group_name from ledger_group", null,
                        commandType: CommandType.Text).ToList();

                    ViewBag.sub_ledger_group = new SelectList(ledger_group, "code", "group_name");

                    //return the ledger to edit
                    ledger = sqlConnection.Query<Ledger>
                       ("get_ledger_per_Id", new { @code = id }, commandType: CommandType.StoredProcedure).SingleOrDefault();

                    return View(ledger);
                }
            }
            catch (Exception ex)
            {
                oError.WriteErrorLog(ex.Message);

                throw new Exception(ex.Message);

            }
        }

        //
        // POST: /Ledger/Edit/5

        [HttpPost]
        public JsonResult Edit(string id, Ledger model)
        {
            try
            {
                ledger_code = id;
                IsNew = false;

                Create(model);
                TempData["Success"] = "Changes saved succesfully";

                return Json(TempData["Success"].ToString(), JsonRequestBehavior.AllowGet);

            }
            catch(Exception ex)
            {
                oError.WriteErrorLog(ex.Message);
                TempData["Error"] = "Details not saved! " + ex.Message;
                return Json(TempData["Error"].ToString(), JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /Ledger/Delete/5

        public ActionResult Delete(string id)
        {
            return View();
        }

        //
        // POST: /Ledger/Delete/5

        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    var affected_row = sqlConnection.Execute
                        ("update ledger set IsDeleted=1 where code=@code",
                        new { ledger_code = id }, commandType: CommandType.Text);
                    return View("Index", ledger);

                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        public JsonResult getSubledgers(string id)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    IEnumerable<Ledger_Group> ledger_group =
                       sqlConnection.Query<Ledger_Group>
                       ("get_ledger_group",
                       new { @class_code = id },
                       commandType: CommandType.StoredProcedure).ToList();

                    var sub_ledgers = new SelectList(ledger_group, "code", "group_name");

                    ViewBag.Ledger_group = sub_ledgers;

                    return Json(ViewBag.Ledger_group, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public JsonResult softDelete(string id)
        {
            try
            {
                using (sqlConnection)
                {
                    sqlConnection.Open();

                    var affected_row = sqlConnection.Execute
                        ("update ledger set IsDeleted=1 where code=@code",
                        new { code = id }, commandType: CommandType.Text);
                    return Json("Deleted", JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

    }
}

mLender/Views/Ledger/Create.cshtml
@model mLender.Models.Ledger
@if (User.Identity.IsAuthenticated)
{
    {

        ViewBag.Title = "Create";
        Layout = "~/Views/Shared/_Layout.cshtml";
        @Html.Partial("~/Views/Shared/_LeftMenu.cshtml")

    }
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


    <!--Data table references-->

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>


    <!--select 2 dropdown search-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />

    <!--sweet alert for message display-->
    @*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
    <script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>

    <!--My custom scripts-->
    <script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>


    <div class="row">

        @using (Html.BeginForm("create", "Ledger", new { ReturnUrl = ViewBag.Returnurl },
            FormMethod.Post, new { @class = "bootstrap-admin-small-form col-lg-10 col-md-10 col-xs-10", @id = "ledger_form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)



        <fieldset>
            <legend style="text-align:center">Add ledger Account</legend>

            <div class="form-group">
                <label>Main Ledger Class</label>
                <div id="main_class">
                    @Html.DropDownList("Class", (SelectList)@ViewBag.main_classes, "--Select Main Ledger--",
                   htmlAttributes: new { @class = "form-control chosen ledger", @onchange = "dropdownChange(this.value)", @id = "#main_class", required = "required" })
                </div>
                @Html.ValidationMessageFor(Model => Model.Class, "", new
                    { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Ledger Group</label>

                @Html.DropDownList("Ledger_group", (SelectList)@ViewBag.Ledgers, "--Select Ledger Group--",
               htmlAttributes: new { @class = "form-control ledger", @disabled = "disabled", @id = "ledger_groups", required = "required" })

            </div>
            @Html.ValidationMessageFor(Model => Model.Ledger_group, "", new { @class = "text-danger" })

            <div class="form-group hidden">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Code)
                </div>
                @Html.TextBoxFor(model => model.Code, @Model.Code,
               htmlAttributes: new { @class = "form-control ledger", @disabled = "disabled", @value = "", @id = "ledger_code", required = "required" })

                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Name</label>

                <input class="form-control ledger" id="name" type="text" name="Name" placeholder="Equity Current Account" required>
            </div>
            @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })

            <div class="form-group">
                <label>Allow Overdraft</label>

                @Html.CheckBoxFor(model => model.Allow_Overdraft)
            </div>

            <div class="form-group">
                <label>Bank</label>

                @Html.CheckBoxFor(model => model.IsBank)
                @Html.ValidationMessageFor(model => model.IsBank)
            </div>

            <p>
                <button class="btn btn-lg btn-xs btn-sm btn-primary" id="btn_submit" type="submit">Save</button>
            </p>
        </fieldset>
        }
        @*call javascript for searching dropdown*@
        <script type="text/javascript">
            $(document).ready(
                $(".chosen").chosen({ no_results_text: "oops! No record found matching the name:  " })
            );
        </script>

        <script type="text/javascript">
            function dropdownChange(val) {
                //alert(val);
                var main_class = document.getElementById("#main_class").value;

                var ledger2 = document.getElementById("ledger_groups");
                ledger2.disabled = false;
                //ledger2.classList.add("chosen");
                getsubledgers(val);

            };

            function getsubledgers(id) {
                let dropdown = $('#ledger_groups');
                //dropdown.classList.add("chosen");
                dropdown.html("");


                dropdown.append('<option selected="true" disabled >Choose ledger group</option>');
                dropdown.prop('selectedIndex', 0);
                const url = '/ledger/getSubledgers/?id=' + id;

                // Populate dropdown with list of ledger group
                $.getJSON(url, function (data) {
                    $.each(data, function (key, entry) {
                        var ledger = [];
                        dropdown.append($('<option></option>').val(entry.Value).text(entry.Text));


                    })
                });

            }

        </script>

    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>



}
else
{
    Response.Redirect("~/account/login");

}

<!--Send to controller-->
<script type="text/javascript">
    function addLedger() {

        // Get form
        var form = $('#ledger_form')[0];
        // Create an FormData object
        var data = new FormData(form);

        jQuery.ajax({
            type: 'Post',
            url: '/ledger/Create',
            data: data,
            processData: false,
            contentType: false,
            success: function (succes_message) {
                swal("", succes_message, "info");


            },
            error: function (request, status, error) {
                swal("Error", error, "warning");

            }
        })
    }
</script>
<!--loop to check if some fields are empty-->
<script type="text/javascript">
    function checkEmptyFields() {


        var anyFieldIsEmpty = $.trim($('.ledger').val()) == "";


        if (anyFieldIsEmpty) {
            swal("", "Fill all the necessary fields", "warning");

            var empty = jQuery(".ledger").filter(function () {
                return jQuery.trim(this.value).length === 0 || jQuery('.loantype').val();
            })
            empty.css("border", "1px solid red");
            //empty.addClass("mandatory");

            return false;
        } else {
            return true;

        }


    }


</script>
<!--submit button-->
<script type="text/javascript">
    jQuery("#btn_submit").on('click', function (e) {
        e.preventDefault();

        if (checkEmptyFields()) {
            addLedger();

        }
    })


</script>

mLender/Views/Ledger/Edit.cshtml
@model mLender.Models.Ledger

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Html.Partial("~/Views/Shared/_LeftMenu.cshtml")


}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<!--Data table references-->

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>


<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />

<!--sweet alert for message display-->
@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>

<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>



@using (Html.BeginForm("edit", "Ledger", new { ReturnUrl = ViewBag.Returnurl }, FormMethod.Post,
    new { @class = "bootstrap-admin-small-form col-lg-10 col-md-10 col-xs-10", @id = "ledger_form" }))


{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit Ledger</legend>

        
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.Class)
            </div>
            @Html.DropDownList("Class", (SelectList)@ViewBag.main_classes, 
                   htmlAttributes: new { @class = "form-control ledger search", @id = "main_class", @onchange = "dropdownChange(this.value)", required = "required" })
            @Html.ValidationMessageFor(model => model.Class, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <div class="editor-label">
                @Html.Label("Ledger Group")
            </div>
            @*@Html.DropDownList("Ledger_group", (SelectList)@ViewBag.ledgers, Model.Ledger_group,
                  htmlAttributes: new
                       {
                           @class = "form-control search ledger",
                           disabled = "disabled",
                      @id = "ledger_groups",
                           required = "required"
                       })*@

            @Html.DropDownList("Ledger_group", (SelectList)@ViewBag.sub_ledger_group,"--Select Ledger Group--",
                 htmlAttributes: new
                      {
                          @class = "form-control search ledger",
                          disabled = "disabled",
                     @id = "ledger_groups",
                          required = "required"
                      })


            @Html.ValidationMessageFor(model => model.Ledger_group, "", new { @class = "text-danger" })
        </div>


        <div class="form-group hidden">
            <div class="editor-label">
                @Html.LabelFor(model => model.Code)
            </div>
            @Html.TextBoxFor(model => model.Code,
           htmlAttributes: new { @class = "form-control ledger", @id = "ledger_code", required = "required" })

            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name,
           htmlAttributes: new { @class = "form-control ledger", @id = "ledger_name", required = "required" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Allow_Overdraft)
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(model => model.Allow_Overdraft)
            @Html.ValidationMessageFor(model => model.Allow_Overdraft)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsBank)
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(model => model.IsBank)
            @Html.ValidationMessageFor(model => model.IsBank)
        </div>

        <p>
            <button class="btn btn-lg btn-sm btn-xs btn-primary" id="btn_submit" type="submit">Save</button>

        </p>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>


    </fieldset>
}


<!--Send to controller-->
<script type="text/javascript">
    function updateLedger() {

        // Get form
        var form = $('#ledger_form')[0];
        // Create an FormData object
        var data = new FormData(form);


        jQuery.ajax({
            type: 'Post',
            url: '/ledger/edit',
            data: data,
            processData: false,
            contentType: false,
            success: function (succes_message) {
                swal("", succes_message, "info");


            },
            error: function (request, status, error) {
                swal("Error", error, "warning");

            }
        })
    }
</script>
<!--loop to check if some fields are empty-->
<script type="text/javascript">
    function checkEmptyFields() {


        var anyFieldIsEmpty = $.trim($('.ledger').val()) == "";


        if (anyFieldIsEmpty) {
            swal("", "Fill all the necessary fields", "warning");

            var empty = jQuery(".ledger").filter(function () {
                return jQuery.trim(this.value).length === 0 || jQuery('.loantype').val();
            })
            empty.css("border", "1px solid red");
            //empty.addClass("mandatory");

            return false;
        } else {
            return true;

        }


    }


</script>
<!--submit button-->
<script type="text/javascript">
    jQuery("#btn_submit").on('click', function (e) {
        e.preventDefault();

        if (checkEmptyFields()) {
            updateLedger();

        }
    })


</script>

<!--when main class change populate sub ledgers accordingly-->
@*<script type="text/javascript">
    function dropdownChange(val) {
        //alert(val);
        var main_class = document.getElementById("main_class").value;


        var ledger2 = document.getElementById("ledger_groups");
        ledger2.disabled = false;
        getsubledgers(val);
    }
    </script>*@

<script type="text/javascript">
    $('.search').select2();
</script>


<script type="text/javascript">
    function dropdownChange(val) {
        //alert(val);
        var main_class = document.getElementById("main_class").value;

        var ledger2 = document.getElementById("ledger_groups");
        ledger2.disabled = false;
        //ledger2.classList.add("chosen");
        getsubledgers(val);

    };

    function getsubledgers(id) {
        let dropdown = $('#ledger_groups');
        //dropdown.classList.add("chosen");
        dropdown.html("");


        dropdown.append('<option selected="true" disabled >Choose ledger group</option>');
        dropdown.prop('selectedIndex', 0);
        const url = '/ledger/getSubledgers/?id=' + id;

        // Populate dropdown with list of ledger group
        $.getJSON(url, function (data) {
            $.each(data, function (key, entry) {
                var ledger = [];
                dropdown.append($('<option></option>').val(entry.Value).text(entry.Text));


            })
        });

    }

</script>

mLender/Views/Ledger/Index.cshtml
@model IEnumerable<mLender.Models.Ledger>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Html.Partial("~/Views/Shared/_LeftMenu.cshtml")

}


<style type="text/css">
    table {
        /*table-layout: fixed;*/
        /*width: 300px;*/
    }

    #table_ledger {
        white-space: nowrap;
        width: 80%;

    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<!--Data table references-->

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>


<!--select 2 dropdown search-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" />

<!--sweet alert for message display-->
@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>

<!--My custom scripts-->
<script type="text/javascript" src="~/Scripts/MyCustomScripts.js"></script>


<div class="panel-heading" style="text-align:center"><h4>Ledger List</h4></div>

<p>
    @Html.ActionLink("New", "Create", new { },
    new { @class = "btn btn-lg btn-sm btn-md btn-success glyphicon  glyphicon-plus", @style = "color:white" })
</p>

<div class="panel panel-default col-md-10 ">

    <div class="bootstrap-admin-panel-content">
        <table class="table table-striped" id="table_ledger">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Code")
                    </th>
                    <th>
                        @Html.DisplayName("Class")
                    </th>
                    <th>
                        @Html.DisplayName("Group")
                    </th>
                    <th>
                        @Html.DisplayName("Name")
                    </th>

                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Class)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ledger_group)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>

                    <td>


                        @Html.ActionLink("Edit", "Edit", new { id = item.Code }, new { @class = "btn btn-lg btn-sm  btn-primary glyphicon glyphicon-pencil glyphicon-white", @style = "color:white" })

                        @Html.ActionLink("delete", "", new { id = item.Code },
                       new
                       {
                           @class = "btn btn-lg btn-sm  btn-danger glyphicon  glyphicon-remove glyphicon-white",
                           @style = "color:white",
                           @id = "delete"
                           //@onclick = "deleteLedger("+item.Code+")"
                       })
                    </td>
                </tr>

            }

        </table>
    </div>
</div>

<!--data tables-->
<script type="text/javascript">

    $('#table_ledger').DataTable(
        {
            "bPaginate": true, "bLengthChange": true, "bFilter": true, "bSort": true, "bInfo": true, "bAutoWidth": true, "aoColumns": [
                null,
                null,
                null, null, null]
        });

</script>